# Generated by Django 4.2.7 on 2023-11-21 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_CRUD', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
